config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount Api::Cost => '/api'
  root "dashboards#index"

  resources :costs
  resources :items
  resources :dashboards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cost.rb
# == Schema Information
#
# Table name: costs
#
#  id         :bigint(8)        not null, primary key
#  category   :string
#  item       :string
#  mount      :integer
#  price      :integer
#  sum        :integer
#  note       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cost < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :cost
  attr_accessor :cost_id
end

app/models/user.rb
class User < ApplicationRecord
  extend Devise::Models

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @costs = costs

    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @costs.to_json(only: [:id, :category]) }
    end
  end

  def new
    @cost = Cost.new
  end

  def create
    cost = costs.new(cost_params)

    respond_to do |format|
      if cost.save
        format.html { redirect_to_ok }
        format.json { render :json => @costs.to_json(only: [:id, :category]) }
      else
        redirect_to_ng
      end
    end
  end

  private

  def costs
    @costs ||= Cost.all
  end

  def cost
    @cost ||= Cost.find params[:id]
  end

  def cost_params
    params.require(:cost).permit(:category)
  end

  def redirect_to_ok
    redirect_to costs_path, notice: 'OK'
  end

  def redirect_to_ng
    redirect_to costs_path, notice: 'NG'
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index

  end

  def show
    @cost = Cost.find params[:id]
    @items = @cost.items
    @summary = @items.sum(:sum).round(2)

    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @items.to_json }
    end
  end

  def create
    cost = Cost.find params[:item][:cost_id]
    item = cost.items.new(item_params)
    item.sum = params[:item][:mount].to_i * params[:item][:price].to_i

    respond_to do |format|
      if item.save
        format.html { redirect_to_ok(cost) }
        format.json { render :json => item.to_json }
      else
        redirect_to_ng(cost)
      end
    end
  end

  def destroy
    ids = params[:item][:ids]
    items = Item.where(id: ids)

    if items.destroy_all
      render json: { status: 'success', code: 200, message: 'Destroy successfully.'}
    else
      render json: { status: 'fail', code: 400, message: 'Destroy fail.'}
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :mount, :price, :sum, :notice)
  end

  def redirect_to_ok(cost)
    redirect_to item_path(cost), notice: 'OK'
  end

  def redirect_to_ng(cost)
    redirect_to item_path(cost), notice: 'NG'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costs/index.html.erb
<costs></costs>

app/views/dashboards/index.html.erb
<dashboard></dashboard>

app/views/items/index.html.erb
hi

app/views/items/show.html.erb
<items cost-id="<%= @cost.id %>" summary="<%= @summary%>"></items>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunny</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body>
    <div id="hello">
      <el-container direction="vertical">
        <site-header cost-path="<%= costs_path %>" current-path="<%= request.path %>"></site-header>
        <el-main>
          <%= yield %>
        </el-main>
      </el-container>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="no-js js-menubar">
  <head>
    <title>Sunny</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body class="animsition page-login-v3 layout-full" style="animation-duration: 800ms; opacity: 1;">
    <div id="hello">
      <el-container direction="vertical">
        <el-main>
          <%= yield %>
        </el-main>
      </el-container>
    </div>
  </body>
</html>

app/views/partial/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark el-main">
  <a class="navbar-brand" href="#">Sunny</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to '總覽', dashboards_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '費用', costs_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
         <%= link_to '員工', costs_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-raised btn-primary my-2 my-sm-0', method: :delete %>
      <% end %>
    </form>
  </div>
</nav>